### ISSUE TITLE
SVD DDNM

### ISSUE THREAD

**Issue by Midnight000** [UCSB-NLP-Chang/CoPaint#2]
Hi, thanks for your contributions in "Towards Coherent Image Inpainting Using Denoising Diffusion Implicit Models" and the integration of the recent diffusion inpainting methods.
Will you implement SVD DDNM since I found it works much better than the simplified one with the original DDNM code?

**Comment by ghzhang233** [comment]
Hi Midnight000,

Thank you for your interest in our work. Unfortunately, we currently do not have such a plan. One could refer to the authors of the related paper for implementations. Feel free to let me know if there are any other issues with our work.

Regards,
Guanhua
