### ISSUE TITLE
Hello, how can I train this model with my own data

### ISSUE THREAD

**Issue by robot444** [UCSB-NLP-Chang/CoPaint#4]
Hello, how can I train this model with my own data

**Comment by ghzhang233** [comment]
Hi, as we only use pre-trained model in our project, I think it is better to see [guided-diffusion](https://github.com/openai/guided-diffusion) and [lama](https://github.com/advimman/lama) for training instruction. I hope this would help and please let me know if there is anything else that I could help with.
