### ISSUE TITLE
imagenet100 folder is missing

### ISSUE THREAD

**Issue by bttkm82** [UCSB-NLP-Chang/CoPaint#7]
Thank you for the wonderful research. 
However, I couldn't find the imagenet100 folder in the datasets directory. 
Could you please let me know where I can download it?

**Comment by ghzhang233** [comment]
Hi @bttkm82,

Apologies for the delayed response. The “Imagenet 100” folder is intended to include the initial 100 images from the ILSVRC2012 testing set, along with the labels from the validation set. You also have the option to download these files from the provided [link](https://drive.google.com/drive/folders/1CTBHK8udyGejJEob-HTL1MrmtkqC_3gr?usp=sharing
).

Please let me know if there is anything else that I can help with.

Regards,
Guanhua
